# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLN0S5FwjlVpGKEYzLrRByjH19v5aP0_
"""


import random

# Training text
text = """
machine learning is interesting and machine learning is powerful
artificial intelligence and machine learning are related fields
"""

# Step 1: Split text into words
words = text.split()

# Step 2: Build Markov chain dictionary
markov_chain = {}

for i in range(len(words)-1):
    current_word = words[i]
    next_word = words[i+1]

    if current_word not in markov_chain:
        markov_chain[current_word] = []

    markov_chain[current_word].append(next_word)

# Step 3: Generate text
current_word = random.choice(words)
generated_text = [current_word]

for i in range(20):
    if current_word in markov_chain:
        next_word = random.choice(markov_chain[current_word])
        generated_text.append(next_word)
        current_word = next_word
    else:
        break

# Output
print("Generated Text:")
print(" ".join(generated_text))
